AspViewComponents/Models/Person.cs
namespace AspViewComponents.Models;

public class Person
{
    public string? Name { get; init; }
    public string? JoBTitle { get; init; }
}

AspViewComponents/Models/PersonGrid.cs
namespace AspViewComponents.Models;

public class PersonGrid
{
    public string GridTitle { get; init; }
    public IEnumerable<Person> Persons { get; init; }
}

AspViewComponents/Controllers/HomeController.cs
using AspViewComponents.Models;
using Microsoft.AspNetCore.Mvc;

namespace AspViewComponents.Controllers;

public class HomeController : Controller
{
    [Route("/")]
    public IActionResult Index()
    {
        return View();
    }

    [Route("about")]
    public IActionResult About()
    {
        return View();
    }

    [Route("load-people")]
    public IActionResult LoadPeople()
    {
        PersonGrid model = new PersonGrid()
        {
            GridTitle = "Person",
            Persons =
            [
                new Person() {Name = "Ibrahim", JoBTitle = "Captian"},
            new Person() {Name = "Mostafa", JoBTitle = "Theif"},
            new Person() {Name = "Hussien", JoBTitle = "Depressed" }
            ]
        };
        return ViewComponent("Grid", new { grid = model });
    }
}

AspViewComponents/ViewComponents/GridViewComponent.cs
using AspViewComponents.Models;
using Microsoft.AspNetCore.Mvc;

namespace AspViewComponents.ViewComponents;

public class GridViewComponent : ViewComponent
{
    public async Task<IViewComponentResult> InvokeAsync(PersonGrid grid)
    {
        return View(grid);
    }
}

AspViewComponents/Views/Home/About.cshtml
@{
    ViewBag.pageTitle = "About";
}

AspViewComponents/Views/Home/Index.cshtml
@{
    ViewBag.pageTitle = "Home";
    PersonGrid model = new PersonGrid()
    {
        GridTitle = "Person",
        Persons =
        [
            new Person() {Name = "Ibrahim", JoBTitle = "Captian"},
            new Person() {Name = "Mostafa", JoBTitle = "Theif"},
            new Person() {Name = "Hussien", JoBTitle = "Depressed" }
        ]
    };
}

<h1>Home Page</h1>
<button id="load-people-button" type="button" class="button button-blue-back">Load People</button>
<div class="people-section">
    <!-- loaded people -->
</div>
@* @await Component.InvokeAsync("Grid", new { grid = model }) *@
@* <vc:grid grid="model"></vc:grid> *@

<script>
    document.getElementById('load-people-button').addEventListener('click', async () => {
        const response = await fetch('/load-people');
        const htmlContext = await response.text();
        document.querySelector('.people-section').innerHTML += htmlContext;
    });
</script>

AspViewComponents/Views/Shared/Components/Grid/Default.cshtml
@model PersonGrid
<div class="box">
    <h3>@Model.GridTitle</h3>
    <table class="table w-100">
        <thead>
            <tr>
                <th>Name</th>
                <th>Job Title</th>
            </tr>
        </thead>
        <tbody>
            @foreach (Person person in Model.Persons)
            {
                <tr>
                    <td>@person.Name</td>
                    <td>@person.JoBTitle</td>
                </tr>
            }
        </tbody>
    </table>
</div>